mysite/urls.py
from django.conf.urls import url
from django.contrib import admin

admin.autodiscover()

from restaurants.views import menu, list_restaurants, comment, menu_id
from mysite.views import welcome, use_session, session_test, set_c, get_c, index, register
from django.contrib.auth.views import login, logout

urlpatterns = [
    url(r'^get_c/$', get_c),
    url(r'^set_c/$', set_c),
    url(r'^welcome/$', welcome),
    url(r'^use_session/$', use_session),
    url(r'^session_test/$', session_test),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/register/$',register),
    url(r'^$',index),
    url(r'index/^$',index),
    url(r'^menu/$', menu),
    url(r'^menu/(\d{1,5})/$', menu_id),
    url(r'^restaurants_list/$', list_restaurants),
    url(r'^comment/(\d{1,5})/$', comment),
    url(r'^accounts/login/$',login,{'template_name':'login.html'}),
    url(r'^accounts/logout/$',logout,{'template_name':'index.html'}),
]

library/models.py
from __future__ import unicode_literals

from django.db import models

class Author(models.Model):
    name = models.CharField(max_length=30)
    
    def __unicode__(self):
        return self.name

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    
    def __unicode__(self):
        return self.title

restaurants/models.py
from __future__ import unicode_literals

from django.db import models

class Restaurant(models.Model):
    name = models.CharField(max_length=20)
    phone_number = models.CharField(max_length=15)
    address = models.CharField(max_length=50, blank=True)

    def __unicode__(self):
        return self.name
        
class Food(models.Model):
    name = models.CharField(max_length=20)
    price = models.DecimalField(max_digits=3,decimal_places=0)
    comment = models.CharField(max_length=50, blank=True)
    is_spicy = models.BooleanField()
    restaurant = models.ForeignKey(Restaurant)

    def __unicode__(self):
        return self.name

class Comment(models.Model):
    content = models.CharField(max_length=200)
    user = models.CharField(max_length=20)
    email = models.EmailField(max_length=20)
    date_time = models.DateTimeField()
    restaurant = models.ForeignKey(Restaurant)

    def __unicode__(self):
        return self.user + ':' + self.content

    class Meta:
        ordering = ['date_time']
        permissions = (
            ("can_comment", "Can comment", ),
        )

restaurants/forms.py
from django import forms

class CommentForm(forms.Form):
    user = forms.CharField(max_length=20)
    email = forms.EmailField(max_length=20, required=False)
    content = forms.CharField(max_length=200)

library/views.py
from django.shortcuts import render

# Create your views here.

mysite/views.py
# -*- coding: utf-8 -*-
from django.http import HttpResponse, HttpResponseRedirect
from django import template
from django.template.loader import get_template
from django.shortcuts import render_to_response
from django.contrib.sessions.models import Session
from django.contrib import auth
from django.contrib.auth.forms import UserCreationForm

def welcome(request):
    if 'user_name' in request.GET:
        return HttpResponse('Welcome!~'+request.GET['user_name'])
    else:
        return render_to_response('welcome.html',locals())

def use_session(request):
    request.session['lucky_number'] = '8'                               # 設置lucky_number

    if 'lucky_number' in request.session:
        lucky_number = request.session['lucky_number']                # 讀取lucky_number

        response = HttpResponse('Your lucky_number is ' + lucky_number)
    del request.session['lucky_number']                               # 刪除lucky_number
    
    return response

def session_test(request):
    sid = request.COOKIES['sessionid']
    s = Session.objects.get(pk=sid)
    s_info = 'Session ID:' + str(sid) + '<br>Expire_date:' + str(s.expire_date) + '<br>Data:' + str(s.get_decoded())
    return HttpResponse(s_info)

def get_c(request):
    if 'lucky_number' in request.COOKIES:
        return HttpResponse('Your lucky_number is {0}'.format(request.COOKIES['lucky_number']))
    else:
        return HttpResponse('No cookies.') 
        
def set_c(request):
    response = HttpResponse('Set your lucky_number as 8')
    response.set_cookie('lucky_number',8)
    return response

'''
def login(request):

    #如果用戶已經登入，則HttpRequest.user是一個User物件，也就是具名用戶。
    #所以如果使用者已經認證過，我們將他重導回首頁
    if request.user.is_authenticated(): 
        return HttpResponseRedirect('/')

    #如果使用者尚未登入，HttpRequest.user是一個AnonymousUser物件，也就是匿名用戶。
    username = request.POST.get('username', '')
    password = request.POST.get('password', '')

    #使用auth中的authenticate方法來確認用戶
    user = auth.authenticate(username=username, password=password)
    
                            #帳戶沒有被凍結
    if user is not None and user.is_active:
        auth.login(request, user) #真正登入使用者並保持他的登入狀態
        return HttpResponseRedirect('/')
    else:
        return render_to_response('login.html')
'''
def index(request):
    return render_to_response('index.html',locals())
'''
def logout(request):
    auth.logout(request)
    return HttpResponseRedirect('/')
    '''
def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            return HttpResponseRedirect('/accounts/login/')
    else:
        form = UserCreationForm()
    return render_to_response('register.html',locals())

restaurants/views.py
# -*- coding: utf-8 -*-
from django import template
from django.http import HttpResponse, HttpResponseRedirect
from django.template.loader import get_template
from django.template import RequestContext
from django.shortcuts import render_to_response

from django.contrib.auth.decorators import login_required, user_passes_test, permission_required
from restaurants.forms import CommentForm
from restaurants.models import Restaurant, Food, Comment
import datetime


def menu_id(request, id):
    if id:
        r = Restaurant.objects.get(id=id)
        return render_to_response('menu.html',locals())
    else:
        return HttpResponseRedirect("/restaurants_list/")

def menu(request):
    if id:
        r = Restaurant.objects.get(id=request.GET['id'])
        return render_to_response('menu.html',locals())
    else:
        return HttpResponseRedirect("/restaurants_list/")

@login_required
def list_restaurants(request):
    restaurants = Restaurant.objects.all()
    print request.user.user_permissions.all()
    return render_to_response('restaurants_list.html',
                               locals(),
                               context_instance=RequestContext(request))

def user_can_comment(user):
    return user.is_authenticated and user.has_perm('restaurants.can_comment')
    
@user_passes_test(user_can_comment, login_url='/accounts/login/')
def comment(request,id):
    if id:
        r = Restaurant.objects.get(id=id)
    else:
        return HttpResponseRedirect("/restaurants_list/")

    if request.user.is_authenticated and request.user.has_perm('restaurants.can_comment'):
        errors = []
        if 'ok' in request.POST:
            f = CommentForm(request.POST)
            if f.is_valid():
                user = request.POST['user']
                content = request.POST['content']
                email = request.POST['email']
                date_time = datetime.datetime.now()
                c = Comment(user=user, email=email, content=content, date_time=date_time, restaurant=r)
                c.save()
                f = CommentForm()
        else:
            f = CommentForm()
    else:
        return HttpReponseRedirect('/restaurants_list/')
        
    return render_to_response('comments.html',locals())
    

restaurants/templates/comments.html
<!doctype html>
<html>
    <head>
        <title> Comments </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>{{ r.name }}的評價</h2>
        {% if r.comment_set.all %}
            <p>目前共有{{ r.comment_set.all|length }}條評價</p>
            <table>
                <tr>
                    <th>留言者</th>
                    <th>時間</th>
                    <th>評價</th>
                </tr>
            {% for c in r.comment_set.all %}
                <tr>
                    <td> {{ c.user }} </td>
                    <td> {{ c.date_time | date:"F j, Y" }} </td>
                    <td> {{ c.content }} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>無評價</p>
        {% endif %}

        <br /><br />
        {% for e in errors %}
            {{ e }} <br />
        {% endfor %}

        <form action="" method="post">
            {{ f.as_table }}
            <input type="hidden" name="ok" value="yes">
            <input type="submit" value="給予評價">
        </form>
        </form>
    </body>
</html>

restaurants/templates/menu.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>{{ r.name }}的Menu</h2>
        {% if r.food_set.all %}
            <p>店家有{{ r.food_set.all|length }}道菜</p>
            <table>
                <tr>
                    <th>菜名</th>
                    <th>價格</th>
                    <th>註解</th>
                    <th>辣不辣</th>
                </tr>
            {% for food in r.food_set.all %}
                <tr>
                    <td> {{ food.name }} </td>
                    <td> {{ food.price }} </td>
                    <td> {{ food.comment }} </td>
                    <td> {% if food.is_spicy %} 辣 {% else %} 不辣 {% endif %} </td>
                </tr>
            {% endfor %}
            </table>
        {% else %}
            <p>直接來店裡坐吧~</p>
        {% endif %}
    </body>
</html>

restaurants/templates/restaurants_list.html
<!doctype html>
<html>
    <head>
        <title> Menu </title>
        <meta charset='utf-8'>
    </head>
    <body>
        <h2>目前的美食有...</h2>
        <form action="/menu/" method="get">
        <table>
            <tr>
                <th>選取</th>
                <th>店名</th>
                <th>電話</th>
                <th>地址</th>
                {% if perms.restaurants.can_comment %}
                    <th>評價</th>
                {% endif %}
            </tr>
            {% for r in restaurants %}
                <tr>
                    <!-- <td> <input type="radio" name="id" value="{{r.id}}"> </td> -->
                    <td> <a href="/menu/{{r.id}}/"> menu </a> </td>
                    <td> {{ r.name }} </td>
                    <td> {{ r.phone_number }} </td>
                    <td> {{ r.address }} </td>
                    {% if perms.restaurants.can_comment %}
                        <td> <a href="/comment/{{r.id}}/"> comment </a> </td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>
        <!-- <button type="submit">觀看menu</button> -->
        </form>
    </body>
</html>

templates/index.html
<html>
    <head>
        <title>Restaurant King</title>
        <meta charset="utf-8">
    </head>
    <body>
        <h2>美食網</h2>
        <p><a href="/accounts/register/">註冊</a></p>
        {% if request.user.is_authenticated %}
            <p>
                {{request.user}} 您已經登入囉~
                <a href="/accounts/logout/">登出</a>
            </p>
            <a href="/restaurants_list/">美食列表</a>
        {% else %}
            <p>您尚未登入喔~<a href="/accounts/login/">登入</a></p>
        {% endif %}
    </body>
</html>

templates/login.html
<!DOCTYPE html>
<html>
    <head>
        <title>login</title>
    </head>
    <body>
    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'django.contrib.auth.views.login' %}">
        {% csrf_token %}
        <table>
            <tr>
                <td>{{ form.username.label_tag }}</td>
                <td>{{ form.username }}</td>
            </tr>
            <tr>
                <td>{{ form.password.label_tag }}</td>
                <td>{{ form.password }}</td>
            </tr>
        </table>

        <input type="submit" value="login" />
        <input type="hidden" name="next" value="{{ next }}" />
    </form>
    </body>
</html>

templates/register.html
<!DOCTYPE html>
<html>
    <head>
        <title>register</title>
    </head>
    <body>
        <h1>註冊新帳號</h1>
    
        <form action="" method="post">
            {{ form.as_p }}
            <input type="submit" value="註冊">
        </form>
    </body>
</html>

templates/welcome.html
<html>
    <head>
        <title> Welcome </title>
    </head>
    <body>
        <form action="" method="get">
            <label for="user_name">您的名字</label>
            <input id="user_name" type="text" name="user_name">
            <input type="submit" value="進入網站">
        </form>
    </body>
</html>